[package]
name = "itj_tiny_deps"
version = "0.1.0"
edition = "2021"

[features]
boxed_array = []
command = []
http = ["time"]
plugin_framework = ["time"]
ipc = ["time"]
ipc_linux = ["ipc", "dep:libc"]
ipc_linux_fd_connection = ["ipc_linux"]
ipc_linux_inet_server = ["ipc_linux", "ipc_linux_inet_client"]
ipc_linux_inet_client = ["ipc_linux", "ipc_linux_fd_connection"]
notification = []
notification_notify_send = ["notification"]
random = []
time = ["random"]

[dependencies]
libc = {version="0.2", optional=true}
serde = {version=">=1.0.228", features=["derive"]}
serde_json = "1.0.149"
